// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfW_UxiED-mkwSjG_cGEjrUis9ZvsXUOU',
    appId: '1:1037450681252:web:6d98d98a6c651bfbd93f31',
    messagingSenderId: '1037450681252',
    projectId: 'fbraplica',
    authDomain: 'fbraplica.firebaseapp.com',
    storageBucket: 'fbraplica.firebasestorage.app',
    measurementId: 'G-FPNLCRCGRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4sbZMoNj0XMCt7klRDJ32pKlzrJUrVPA',
    appId: '1:1037450681252:android:7904babf525379d2d93f31',
    messagingSenderId: '1037450681252',
    projectId: 'fbraplica',
    storageBucket: 'fbraplica.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc2VIXak_zNNJRedFnZXgU1D1x_zIU9hk',
    appId: '1:1037450681252:ios:d3e6a1e842b452d8d93f31',
    messagingSenderId: '1037450681252',
    projectId: 'fbraplica',
    storageBucket: 'fbraplica.firebasestorage.app',
    iosBundleId: 'com.example.fbreplica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc2VIXak_zNNJRedFnZXgU1D1x_zIU9hk',
    appId: '1:1037450681252:ios:d3e6a1e842b452d8d93f31',
    messagingSenderId: '1037450681252',
    projectId: 'fbraplica',
    storageBucket: 'fbraplica.firebasestorage.app',
    iosBundleId: 'com.example.fbreplica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfW_UxiED-mkwSjG_cGEjrUis9ZvsXUOU',
    appId: '1:1037450681252:web:4017dd92a79d3c39d93f31',
    messagingSenderId: '1037450681252',
    projectId: 'fbraplica',
    authDomain: 'fbraplica.firebaseapp.com',
    storageBucket: 'fbraplica.firebasestorage.app',
    measurementId: 'G-9JDJEHYXR3',
  );
}
